// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum TransportKind: Int {
  case daily = 0
  case smallWebRtc = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct PipecatClientOptions {
  var kind: TransportKind
  var enableMic: Bool
  var enableCam: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PipecatClientOptions? {
    let kind = pigeonVar_list[0] as! TransportKind
    let enableMic = pigeonVar_list[1] as! Bool
    let enableCam = pigeonVar_list[2] as! Bool

    return PipecatClientOptions(
      kind: kind,
      enableMic: enableMic,
      enableCam: enableCam
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      enableMic,
      enableCam,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct APIRequest {
  var endpoint: String
  var headers: [String: String]
  var requestData: String? = nil
  var timeoutMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> APIRequest? {
    let endpoint = pigeonVar_list[0] as! String
    let headers = pigeonVar_list[1] as! [String: String]
    let requestData: String? = nilOrValue(pigeonVar_list[2])
    let timeoutMs: Int64? = nilOrValue(pigeonVar_list[3])

    return APIRequest(
      endpoint: endpoint,
      headers: headers,
      requestData: requestData,
      timeoutMs: timeoutMs
    )
  }
  func toList() -> [Any?] {
    return [
      endpoint,
      headers,
      requestData,
      timeoutMs,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SendTextOptions {
  var runImmediately: Bool? = nil
  var audioResponse: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SendTextOptions? {
    let runImmediately: Bool? = nilOrValue(pigeonVar_list[0])
    let audioResponse: Bool? = nilOrValue(pigeonVar_list[1])

    return SendTextOptions(
      runImmediately: runImmediately,
      audioResponse: audioResponse
    )
  }
  func toList() -> [Any?] {
    return [
      runImmediately,
      audioResponse,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MediaDeviceInfo {
  var id: String
  var label: String
  var type: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaDeviceInfo? {
    let id = pigeonVar_list[0] as! String
    let label = pigeonVar_list[1] as! String
    let type = pigeonVar_list[2] as! String

    return MediaDeviceInfo(
      id: id,
      label: label,
      type: type
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      label,
      type,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Transcript {
  var text: String
  var finalStatus: Bool? = nil
  var timestamp: String? = nil
  var userId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Transcript? {
    let text = pigeonVar_list[0] as! String
    let finalStatus: Bool? = nilOrValue(pigeonVar_list[1])
    let timestamp: String? = nilOrValue(pigeonVar_list[2])
    let userId: String? = nilOrValue(pigeonVar_list[3])

    return Transcript(
      text: text,
      finalStatus: finalStatus,
      timestamp: timestamp,
      userId: userId
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      finalStatus,
      timestamp,
      userId,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BotOutputData {
  var text: String
  var spoken: Bool
  var aggregatedBy: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BotOutputData? {
    let text = pigeonVar_list[0] as! String
    let spoken = pigeonVar_list[1] as! Bool
    let aggregatedBy = pigeonVar_list[2] as! String

    return BotOutputData(
      text: text,
      spoken: spoken,
      aggregatedBy: aggregatedBy
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      spoken,
      aggregatedBy,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PipecatMetricsData {
  var processor: String
  var value: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PipecatMetricsData? {
    let processor = pigeonVar_list[0] as! String
    let value = pigeonVar_list[1] as! Double

    return PipecatMetricsData(
      processor: processor,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      processor,
      value,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PipecatMetrics {
  var processing: [PipecatMetricsData?]? = nil
  var ttfb: [PipecatMetricsData?]? = nil
  var characters: [PipecatMetricsData?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PipecatMetrics? {
    let processing: [PipecatMetricsData?]? = nilOrValue(pigeonVar_list[0])
    let ttfb: [PipecatMetricsData?]? = nilOrValue(pigeonVar_list[1])
    let characters: [PipecatMetricsData?]? = nilOrValue(pigeonVar_list[2])

    return PipecatMetrics(
      processing: processing,
      ttfb: ttfb,
      characters: characters
    )
  }
  func toList() -> [Any?] {
    return [
      processing,
      ttfb,
      characters,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LLMFunctionCallData {
  var functionName: String
  var toolCallID: String
  var args: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LLMFunctionCallData? {
    let functionName = pigeonVar_list[0] as! String
    let toolCallID = pigeonVar_list[1] as! String
    let args = pigeonVar_list[2] as! String

    return LLMFunctionCallData(
      functionName: functionName,
      toolCallID: toolCallID,
      args: args
    )
  }
  func toList() -> [Any?] {
    return [
      functionName,
      toolCallID,
      args,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BotReadyData {
  var version: String
  var about: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BotReadyData? {
    let version = pigeonVar_list[0] as! String
    let about: String? = nilOrValue(pigeonVar_list[1])

    return BotReadyData(
      version: version,
      about: about
    )
  }
  func toList() -> [Any?] {
    return [
      version,
      about,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Participant {
  var id: String
  var name: String? = nil
  var local: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Participant? {
    let id = pigeonVar_list[0] as! String
    let name: String? = nilOrValue(pigeonVar_list[1])
    let local = pigeonVar_list[2] as! Bool

    return Participant(
      id: id,
      name: name,
      local: local
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      local,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MediaStreamTrack {
  var id: String
  var kind: String
  var enabled: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaStreamTrack? {
    let id = pigeonVar_list[0] as! String
    let kind = pigeonVar_list[1] as! String
    let enabled = pigeonVar_list[2] as! Bool

    return MediaStreamTrack(
      id: id,
      kind: kind,
      enabled: enabled
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      kind,
      enabled,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ParticipantTracks {
  var video: MediaStreamTrack? = nil
  var audio: MediaStreamTrack? = nil
  var screen: MediaStreamTrack? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ParticipantTracks? {
    let video: MediaStreamTrack? = nilOrValue(pigeonVar_list[0])
    let audio: MediaStreamTrack? = nilOrValue(pigeonVar_list[1])
    let screen: MediaStreamTrack? = nilOrValue(pigeonVar_list[2])

    return ParticipantTracks(
      video: video,
      audio: audio,
      screen: screen
    )
  }
  func toList() -> [Any?] {
    return [
      video,
      audio,
      screen,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Tracks {
  var local: ParticipantTracks
  var bot: ParticipantTracks? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Tracks? {
    let local = pigeonVar_list[0] as! ParticipantTracks
    let bot: ParticipantTracks? = nilOrValue(pigeonVar_list[1])

    return Tracks(
      local: local,
      bot: bot
    )
  }
  func toList() -> [Any?] {
    return [
      local,
      bot,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BotLLMSearchResponseData {
  var query: String
  var results: [String?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BotLLMSearchResponseData? {
    let query = pigeonVar_list[0] as! String
    let results = pigeonVar_list[1] as! [String?]

    return BotLLMSearchResponseData(
      query: query,
      results: results
    )
  }
  func toList() -> [Any?] {
    return [
      query,
      results,
    ]
  }
}

private class PipecatApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return TransportKind(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return PipecatClientOptions.fromList(self.readValue() as! [Any?])
    case 131:
      return APIRequest.fromList(self.readValue() as! [Any?])
    case 132:
      return SendTextOptions.fromList(self.readValue() as! [Any?])
    case 133:
      return MediaDeviceInfo.fromList(self.readValue() as! [Any?])
    case 134:
      return Transcript.fromList(self.readValue() as! [Any?])
    case 135:
      return BotOutputData.fromList(self.readValue() as! [Any?])
    case 136:
      return PipecatMetricsData.fromList(self.readValue() as! [Any?])
    case 137:
      return PipecatMetrics.fromList(self.readValue() as! [Any?])
    case 138:
      return LLMFunctionCallData.fromList(self.readValue() as! [Any?])
    case 139:
      return BotReadyData.fromList(self.readValue() as! [Any?])
    case 140:
      return Participant.fromList(self.readValue() as! [Any?])
    case 141:
      return MediaStreamTrack.fromList(self.readValue() as! [Any?])
    case 142:
      return ParticipantTracks.fromList(self.readValue() as! [Any?])
    case 143:
      return Tracks.fromList(self.readValue() as! [Any?])
    case 144:
      return BotLLMSearchResponseData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PipecatApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? TransportKind {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PipecatClientOptions {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? APIRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? SendTextOptions {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? MediaDeviceInfo {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? Transcript {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? BotOutputData {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? PipecatMetricsData {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? PipecatMetrics {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? LLMFunctionCallData {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? BotReadyData {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? Participant {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? MediaStreamTrack {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? ParticipantTracks {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? Tracks {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? BotLLMSearchResponseData {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PipecatApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PipecatApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PipecatApiPigeonCodecWriter(data: data)
  }
}

class PipecatApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PipecatApiPigeonCodec(readerWriter: PipecatApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PipecatClientApi {
  func initialize(options: PipecatClientOptions, completion: @escaping (Result<Void, Error>) -> Void)
  func initDevices(completion: @escaping (Result<Void, Error>) -> Void)
  func startBot(request: APIRequest, completion: @escaping (Result<String, Error>) -> Void)
  func connect(transportParamsJson: String, completion: @escaping (Result<Void, Error>) -> Void)
  func startBotAndConnect(request: APIRequest, completion: @escaping (Result<Void, Error>) -> Void)
  func disconnect(completion: @escaping (Result<Void, Error>) -> Void)
  func disconnectBot() throws
  func sendClientMessage(msgType: String, dataJson: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func sendClientRequest(msgType: String, dataJson: String?, completion: @escaping (Result<String, Error>) -> Void)
  func sendText(content: String, options: SendTextOptions?, completion: @escaping (Result<Void, Error>) -> Void)
  func getAllMics() throws -> [MediaDeviceInfo?]
  func getAllCams() throws -> [MediaDeviceInfo?]
  func getAllSpeakers() throws -> [MediaDeviceInfo?]
  func selectedMic() throws -> MediaDeviceInfo?
  func selectedCam() throws -> MediaDeviceInfo?
  func selectedSpeaker() throws -> MediaDeviceInfo?
  func updateMic(micId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func updateCam(camId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func updateSpeaker(speakerId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func enableMic(enable: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  func enableCam(enable: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  func isMicEnabled() throws -> Bool
  func isCamEnabled() throws -> Bool
  func getTracks() throws -> Tracks
  func getState() throws -> String
  func getVersion() throws -> String
  func release(completion: @escaping (Result<Void, Error>) -> Void)
  func sendAction(dataJson: String, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PipecatClientApiSetup {
  static var codec: FlutterStandardMessageCodec { PipecatApiPigeonCodec.shared }
  /// Sets up an instance of `PipecatClientApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PipecatClientApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! PipecatClientOptions
        api.initialize(options: optionsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let initDevicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.initDevices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initDevicesChannel.setMessageHandler { _, reply in
        api.initDevices { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initDevicesChannel.setMessageHandler(nil)
    }
    let startBotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.startBot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startBotChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! APIRequest
        api.startBot(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startBotChannel.setMessageHandler(nil)
    }
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.connect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let transportParamsJsonArg = args[0] as! String
        api.connect(transportParamsJson: transportParamsJsonArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    let startBotAndConnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.startBotAndConnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startBotAndConnectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! APIRequest
        api.startBotAndConnect(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startBotAndConnectChannel.setMessageHandler(nil)
    }
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { _, reply in
        api.disconnect { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    let disconnectBotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.disconnectBot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectBotChannel.setMessageHandler { _, reply in
        do {
          try api.disconnectBot()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disconnectBotChannel.setMessageHandler(nil)
    }
    let sendClientMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.sendClientMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendClientMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let msgTypeArg = args[0] as! String
        let dataJsonArg: String? = nilOrValue(args[1])
        api.sendClientMessage(msgType: msgTypeArg, dataJson: dataJsonArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendClientMessageChannel.setMessageHandler(nil)
    }
    let sendClientRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.sendClientRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendClientRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let msgTypeArg = args[0] as! String
        let dataJsonArg: String? = nilOrValue(args[1])
        api.sendClientRequest(msgType: msgTypeArg, dataJson: dataJsonArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendClientRequestChannel.setMessageHandler(nil)
    }
    let sendTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.sendText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendTextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let contentArg = args[0] as! String
        let optionsArg: SendTextOptions? = nilOrValue(args[1])
        api.sendText(content: contentArg, options: optionsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendTextChannel.setMessageHandler(nil)
    }
    let getAllMicsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.getAllMics\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAllMicsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAllMics()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAllMicsChannel.setMessageHandler(nil)
    }
    let getAllCamsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.getAllCams\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAllCamsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAllCams()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAllCamsChannel.setMessageHandler(nil)
    }
    let getAllSpeakersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.getAllSpeakers\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAllSpeakersChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAllSpeakers()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAllSpeakersChannel.setMessageHandler(nil)
    }
    let selectedMicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.selectedMic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      selectedMicChannel.setMessageHandler { _, reply in
        do {
          let result = try api.selectedMic()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      selectedMicChannel.setMessageHandler(nil)
    }
    let selectedCamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.selectedCam\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      selectedCamChannel.setMessageHandler { _, reply in
        do {
          let result = try api.selectedCam()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      selectedCamChannel.setMessageHandler(nil)
    }
    let selectedSpeakerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.selectedSpeaker\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      selectedSpeakerChannel.setMessageHandler { _, reply in
        do {
          let result = try api.selectedSpeaker()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      selectedSpeakerChannel.setMessageHandler(nil)
    }
    let updateMicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.updateMic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateMicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let micIdArg = args[0] as! String
        api.updateMic(micId: micIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateMicChannel.setMessageHandler(nil)
    }
    let updateCamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.updateCam\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateCamChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let camIdArg = args[0] as! String
        api.updateCam(camId: camIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateCamChannel.setMessageHandler(nil)
    }
    let updateSpeakerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.updateSpeaker\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateSpeakerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let speakerIdArg = args[0] as! String
        api.updateSpeaker(speakerId: speakerIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateSpeakerChannel.setMessageHandler(nil)
    }
    let enableMicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.enableMic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enableMicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enableArg = args[0] as! Bool
        api.enableMic(enable: enableArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      enableMicChannel.setMessageHandler(nil)
    }
    let enableCamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.enableCam\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enableCamChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enableArg = args[0] as! Bool
        api.enableCam(enable: enableArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      enableCamChannel.setMessageHandler(nil)
    }
    let isMicEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.isMicEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isMicEnabledChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isMicEnabled()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isMicEnabledChannel.setMessageHandler(nil)
    }
    let isCamEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.isCamEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isCamEnabledChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isCamEnabled()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isCamEnabledChannel.setMessageHandler(nil)
    }
    let getTracksChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.getTracks\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getTracksChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getTracks()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getTracksChannel.setMessageHandler(nil)
    }
    let getStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.getState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getStateChannel.setMessageHandler(nil)
    }
    let getVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.getVersion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getVersionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getVersion()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getVersionChannel.setMessageHandler(nil)
    }
    let releaseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.release\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      releaseChannel.setMessageHandler { _, reply in
        api.release { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      releaseChannel.setMessageHandler(nil)
    }
    let sendActionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.sendAction\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendActionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let dataJsonArg = args[0] as! String
        api.sendAction(dataJson: dataJsonArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendActionChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol PipecatClientCallbacksProtocol {
  func onConnected(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onDisconnected(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onTransportStateChanged(state stateArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBotReady(botReadyData botReadyDataArg: BotReadyData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBackendError(message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onLocalAudioLevel(level levelArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onRemoteAudioLevel(level levelArg: Double, participantId participantIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBotStartedSpeaking(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBotStoppedSpeaking(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onUserStartedSpeaking(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onUserStoppedSpeaking(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onUserTranscript(transcript transcriptArg: Transcript, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBotTranscript(text textArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBotLlmText(text textArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBotTtsText(text textArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBotOutput(data dataArg: BotOutputData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBotLlmStarted(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBotLlmStopped(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBotTtsStarted(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBotTtsStopped(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onLlmFunctionCall(data dataArg: LLMFunctionCallData, completion: @escaping (Result<String?, PigeonError>) -> Void)
  func onMetrics(metrics metricsArg: PipecatMetrics, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onServerMessage(dataJson dataJsonArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onMessageError(message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onParticipantJoined(participant participantArg: Participant, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onParticipantLeft(participant participantArg: Participant, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onParticipantUpdated(participant participantArg: Participant, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onTracksUpdated(tracks tracksArg: Tracks, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAvailableCamsUpdated(cams camsArg: [MediaDeviceInfo?], completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAvailableMicsUpdated(mics micsArg: [MediaDeviceInfo?], completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAvailableSpeakersUpdated(speakers speakersArg: [MediaDeviceInfo?], completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onCamUpdated(cam camArg: MediaDeviceInfo, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onMicUpdated(mic micArg: MediaDeviceInfo, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onSpeakerUpdated(speaker speakerArg: MediaDeviceInfo, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBotLLMSearchResponse(response responseArg: BotLLMSearchResponseData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBotConnected(participant participantArg: Participant, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBotDisconnected(participant participantArg: Participant, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBotStarted(dataJson dataJsonArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onTrackStarted(trackId trackIdArg: String, participant participantArg: Participant, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onTrackStopped(trackId trackIdArg: String, participant participantArg: Participant, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onScreenTrackStarted(trackId trackIdArg: String, participant participantArg: Participant, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onScreenTrackStopped(trackId trackIdArg: String, participant participantArg: Participant, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onScreenShareError(message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onInputsUpdated(camera cameraArg: Bool, mic micArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onGenericError(message messageArg: String, code codeArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class PipecatClientCallbacks: PipecatClientCallbacksProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PipecatApiPigeonCodec {
    return PipecatApiPigeonCodec.shared
  }
  func onConnected(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onConnected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onDisconnected(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onDisconnected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onTransportStateChanged(state stateArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onTransportStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onBotReady(botReadyData botReadyDataArg: BotReadyData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotReady\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([botReadyDataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onBackendError(message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBackendError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onLocalAudioLevel(level levelArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onLocalAudioLevel\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([levelArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onRemoteAudioLevel(level levelArg: Double, participantId participantIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onRemoteAudioLevel\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([levelArg, participantIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onBotStartedSpeaking(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotStartedSpeaking\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onBotStoppedSpeaking(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotStoppedSpeaking\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onUserStartedSpeaking(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onUserStartedSpeaking\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onUserStoppedSpeaking(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onUserStoppedSpeaking\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onUserTranscript(transcript transcriptArg: Transcript, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onUserTranscript\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([transcriptArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onBotTranscript(text textArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotTranscript\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([textArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onBotLlmText(text textArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotLlmText\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([textArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onBotTtsText(text textArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotTtsText\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([textArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onBotOutput(data dataArg: BotOutputData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotOutput\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([dataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onBotLlmStarted(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotLlmStarted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onBotLlmStopped(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotLlmStopped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onBotTtsStarted(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotTtsStarted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onBotTtsStopped(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotTtsStopped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onLlmFunctionCall(data dataArg: LLMFunctionCallData, completion: @escaping (Result<String?, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onLlmFunctionCall\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([dataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        let result: String? = nilOrValue(listResponse[0])
        completion(.success(result))
      }
    }
  }
  func onMetrics(metrics metricsArg: PipecatMetrics, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onMetrics\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([metricsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onServerMessage(dataJson dataJsonArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onServerMessage\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([dataJsonArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onMessageError(message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onMessageError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onParticipantJoined(participant participantArg: Participant, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onParticipantJoined\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([participantArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onParticipantLeft(participant participantArg: Participant, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onParticipantLeft\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([participantArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onParticipantUpdated(participant participantArg: Participant, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onParticipantUpdated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([participantArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onTracksUpdated(tracks tracksArg: Tracks, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onTracksUpdated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([tracksArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onAvailableCamsUpdated(cams camsArg: [MediaDeviceInfo?], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onAvailableCamsUpdated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([camsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onAvailableMicsUpdated(mics micsArg: [MediaDeviceInfo?], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onAvailableMicsUpdated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([micsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onAvailableSpeakersUpdated(speakers speakersArg: [MediaDeviceInfo?], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onAvailableSpeakersUpdated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([speakersArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onCamUpdated(cam camArg: MediaDeviceInfo, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onCamUpdated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([camArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onMicUpdated(mic micArg: MediaDeviceInfo, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onMicUpdated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([micArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onSpeakerUpdated(speaker speakerArg: MediaDeviceInfo, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onSpeakerUpdated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([speakerArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onBotLLMSearchResponse(response responseArg: BotLLMSearchResponseData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotLLMSearchResponse\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([responseArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onBotConnected(participant participantArg: Participant, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotConnected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([participantArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onBotDisconnected(participant participantArg: Participant, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotDisconnected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([participantArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onBotStarted(dataJson dataJsonArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotStarted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([dataJsonArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onTrackStarted(trackId trackIdArg: String, participant participantArg: Participant, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onTrackStarted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([trackIdArg, participantArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onTrackStopped(trackId trackIdArg: String, participant participantArg: Participant, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onTrackStopped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([trackIdArg, participantArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onScreenTrackStarted(trackId trackIdArg: String, participant participantArg: Participant, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onScreenTrackStarted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([trackIdArg, participantArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onScreenTrackStopped(trackId trackIdArg: String, participant participantArg: Participant, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onScreenTrackStopped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([trackIdArg, participantArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onScreenShareError(message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onScreenShareError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onInputsUpdated(camera cameraArg: Bool, mic micArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onInputsUpdated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([cameraArg, micArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onGenericError(message messageArg: String, code codeArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onGenericError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([messageArg, codeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
