// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

enum TransportKind {
  daily,
  smallWebRtc,
}

class PipecatClientOptions {
  PipecatClientOptions({
    required this.kind,
    required this.enableMic,
    required this.enableCam,
  });

  TransportKind kind;

  bool enableMic;

  bool enableCam;

  Object encode() {
    return <Object?>[
      kind,
      enableMic,
      enableCam,
    ];
  }

  static PipecatClientOptions decode(Object result) {
    result as List<Object?>;
    return PipecatClientOptions(
      kind: result[0]! as TransportKind,
      enableMic: result[1]! as bool,
      enableCam: result[2]! as bool,
    );
  }
}

class APIRequest {
  APIRequest({
    required this.endpoint,
    required this.headers,
    this.requestData,
    this.timeoutMs,
  });

  String endpoint;

  Map<String, String> headers;

  String? requestData;

  int? timeoutMs;

  Object encode() {
    return <Object?>[
      endpoint,
      headers,
      requestData,
      timeoutMs,
    ];
  }

  static APIRequest decode(Object result) {
    result as List<Object?>;
    return APIRequest(
      endpoint: result[0]! as String,
      headers: (result[1] as Map<Object?, Object?>?)!.cast<String, String>(),
      requestData: result[2] as String?,
      timeoutMs: result[3] as int?,
    );
  }
}

class SendTextOptions {
  SendTextOptions({
    this.runImmediately,
    this.audioResponse,
  });

  bool? runImmediately;

  bool? audioResponse;

  Object encode() {
    return <Object?>[
      runImmediately,
      audioResponse,
    ];
  }

  static SendTextOptions decode(Object result) {
    result as List<Object?>;
    return SendTextOptions(
      runImmediately: result[0] as bool?,
      audioResponse: result[1] as bool?,
    );
  }
}

class MediaDeviceInfo {
  MediaDeviceInfo({
    required this.id,
    required this.label,
    required this.type,
  });

  String id;

  String label;

  String type;

  Object encode() {
    return <Object?>[
      id,
      label,
      type,
    ];
  }

  static MediaDeviceInfo decode(Object result) {
    result as List<Object?>;
    return MediaDeviceInfo(
      id: result[0]! as String,
      label: result[1]! as String,
      type: result[2]! as String,
    );
  }
}

class Transcript {
  Transcript({
    required this.text,
    this.finalStatus,
    this.timestamp,
    this.userId,
  });

  String text;

  bool? finalStatus;

  String? timestamp;

  String? userId;

  Object encode() {
    return <Object?>[
      text,
      finalStatus,
      timestamp,
      userId,
    ];
  }

  static Transcript decode(Object result) {
    result as List<Object?>;
    return Transcript(
      text: result[0]! as String,
      finalStatus: result[1] as bool?,
      timestamp: result[2] as String?,
      userId: result[3] as String?,
    );
  }
}

class BotOutputData {
  BotOutputData({
    required this.text,
    required this.spoken,
    required this.aggregatedBy,
  });

  String text;

  bool spoken;

  String aggregatedBy;

  Object encode() {
    return <Object?>[
      text,
      spoken,
      aggregatedBy,
    ];
  }

  static BotOutputData decode(Object result) {
    result as List<Object?>;
    return BotOutputData(
      text: result[0]! as String,
      spoken: result[1]! as bool,
      aggregatedBy: result[2]! as String,
    );
  }
}

class PipecatMetricsData {
  PipecatMetricsData({
    required this.processor,
    required this.value,
  });

  String processor;

  double value;

  Object encode() {
    return <Object?>[
      processor,
      value,
    ];
  }

  static PipecatMetricsData decode(Object result) {
    result as List<Object?>;
    return PipecatMetricsData(
      processor: result[0]! as String,
      value: result[1]! as double,
    );
  }
}

class PipecatMetrics {
  PipecatMetrics({
    this.processing,
    this.ttfb,
    this.characters,
  });

  List<PipecatMetricsData?>? processing;

  List<PipecatMetricsData?>? ttfb;

  List<PipecatMetricsData?>? characters;

  Object encode() {
    return <Object?>[
      processing,
      ttfb,
      characters,
    ];
  }

  static PipecatMetrics decode(Object result) {
    result as List<Object?>;
    return PipecatMetrics(
      processing: (result[0] as List<Object?>?)?.cast<PipecatMetricsData?>(),
      ttfb: (result[1] as List<Object?>?)?.cast<PipecatMetricsData?>(),
      characters: (result[2] as List<Object?>?)?.cast<PipecatMetricsData?>(),
    );
  }
}

class LLMFunctionCallData {
  LLMFunctionCallData({
    required this.functionName,
    required this.toolCallID,
    required this.args,
  });

  String functionName;

  String toolCallID;

  String args;

  Object encode() {
    return <Object?>[
      functionName,
      toolCallID,
      args,
    ];
  }

  static LLMFunctionCallData decode(Object result) {
    result as List<Object?>;
    return LLMFunctionCallData(
      functionName: result[0]! as String,
      toolCallID: result[1]! as String,
      args: result[2]! as String,
    );
  }
}

class BotReadyData {
  BotReadyData({
    required this.version,
    this.about,
  });

  String version;

  String? about;

  Object encode() {
    return <Object?>[
      version,
      about,
    ];
  }

  static BotReadyData decode(Object result) {
    result as List<Object?>;
    return BotReadyData(
      version: result[0]! as String,
      about: result[1] as String?,
    );
  }
}

class Participant {
  Participant({
    required this.id,
    this.name,
    required this.local,
  });

  String id;

  String? name;

  bool local;

  Object encode() {
    return <Object?>[
      id,
      name,
      local,
    ];
  }

  static Participant decode(Object result) {
    result as List<Object?>;
    return Participant(
      id: result[0]! as String,
      name: result[1] as String?,
      local: result[2]! as bool,
    );
  }
}

class MediaStreamTrack {
  MediaStreamTrack({
    required this.id,
    required this.kind,
    required this.enabled,
  });

  String id;

  String kind;

  bool enabled;

  Object encode() {
    return <Object?>[
      id,
      kind,
      enabled,
    ];
  }

  static MediaStreamTrack decode(Object result) {
    result as List<Object?>;
    return MediaStreamTrack(
      id: result[0]! as String,
      kind: result[1]! as String,
      enabled: result[2]! as bool,
    );
  }
}

class ParticipantTracks {
  ParticipantTracks({
    this.video,
    this.audio,
    this.screen,
  });

  MediaStreamTrack? video;

  MediaStreamTrack? audio;

  MediaStreamTrack? screen;

  Object encode() {
    return <Object?>[
      video,
      audio,
      screen,
    ];
  }

  static ParticipantTracks decode(Object result) {
    result as List<Object?>;
    return ParticipantTracks(
      video: result[0] as MediaStreamTrack?,
      audio: result[1] as MediaStreamTrack?,
      screen: result[2] as MediaStreamTrack?,
    );
  }
}

class Tracks {
  Tracks({
    required this.local,
    this.bot,
  });

  ParticipantTracks local;

  ParticipantTracks? bot;

  Object encode() {
    return <Object?>[
      local,
      bot,
    ];
  }

  static Tracks decode(Object result) {
    result as List<Object?>;
    return Tracks(
      local: result[0]! as ParticipantTracks,
      bot: result[1] as ParticipantTracks?,
    );
  }
}

class BotLLMSearchResponseData {
  BotLLMSearchResponseData({
    required this.query,
    required this.results,
  });

  String query;

  List<String?> results;

  Object encode() {
    return <Object?>[
      query,
      results,
    ];
  }

  static BotLLMSearchResponseData decode(Object result) {
    result as List<Object?>;
    return BotLLMSearchResponseData(
      query: result[0]! as String,
      results: (result[1] as List<Object?>?)!.cast<String?>(),
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is TransportKind) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is PipecatClientOptions) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is APIRequest) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is SendTextOptions) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is MediaDeviceInfo) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is Transcript) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is BotOutputData) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is PipecatMetricsData) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is PipecatMetrics) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is LLMFunctionCallData) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is BotReadyData) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is Participant) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is MediaStreamTrack) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is ParticipantTracks) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is Tracks) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is BotLLMSearchResponseData) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : TransportKind.values[value];
      case 130: 
        return PipecatClientOptions.decode(readValue(buffer)!);
      case 131: 
        return APIRequest.decode(readValue(buffer)!);
      case 132: 
        return SendTextOptions.decode(readValue(buffer)!);
      case 133: 
        return MediaDeviceInfo.decode(readValue(buffer)!);
      case 134: 
        return Transcript.decode(readValue(buffer)!);
      case 135: 
        return BotOutputData.decode(readValue(buffer)!);
      case 136: 
        return PipecatMetricsData.decode(readValue(buffer)!);
      case 137: 
        return PipecatMetrics.decode(readValue(buffer)!);
      case 138: 
        return LLMFunctionCallData.decode(readValue(buffer)!);
      case 139: 
        return BotReadyData.decode(readValue(buffer)!);
      case 140: 
        return Participant.decode(readValue(buffer)!);
      case 141: 
        return MediaStreamTrack.decode(readValue(buffer)!);
      case 142: 
        return ParticipantTracks.decode(readValue(buffer)!);
      case 143: 
        return Tracks.decode(readValue(buffer)!);
      case 144: 
        return BotLLMSearchResponseData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class PipecatClientApi {
  /// Constructor for [PipecatClientApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PipecatClientApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize(PipecatClientOptions options) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.initialize$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[options]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> initDevices() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.initDevices$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<String> startBot(APIRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.startBot$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<void> connect(String transportParamsJson) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.connect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[transportParamsJson]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> startBotAndConnect(APIRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.startBotAndConnect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> disconnect() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.disconnect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> disconnectBot() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.disconnectBot$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> sendClientMessage(String msgType, String? dataJson) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.sendClientMessage$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[msgType, dataJson]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<String> sendClientRequest(String msgType, String? dataJson) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.sendClientRequest$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[msgType, dataJson]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<void> sendText(String content, SendTextOptions? options) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.sendText$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[content, options]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<List<MediaDeviceInfo?>> getAllMics() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.getAllMics$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<MediaDeviceInfo?>();
    }
  }

  Future<List<MediaDeviceInfo?>> getAllCams() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.getAllCams$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<MediaDeviceInfo?>();
    }
  }

  Future<List<MediaDeviceInfo?>> getAllSpeakers() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.getAllSpeakers$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<MediaDeviceInfo?>();
    }
  }

  Future<MediaDeviceInfo?> selectedMic() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.selectedMic$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as MediaDeviceInfo?);
    }
  }

  Future<MediaDeviceInfo?> selectedCam() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.selectedCam$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as MediaDeviceInfo?);
    }
  }

  Future<MediaDeviceInfo?> selectedSpeaker() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.selectedSpeaker$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as MediaDeviceInfo?);
    }
  }

  Future<void> updateMic(String micId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.updateMic$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[micId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> updateCam(String camId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.updateCam$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[camId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> updateSpeaker(String speakerId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.updateSpeaker$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[speakerId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> enableMic(bool enable) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.enableMic$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[enable]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> enableCam(bool enable) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.enableCam$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[enable]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<bool> isMicEnabled() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.isMicEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> isCamEnabled() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.isCamEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<Tracks> getTracks() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.getTracks$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as Tracks?)!;
    }
  }

  Future<String> getState() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.getState$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<String> getVersion() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.getVersion$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<void> release() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.release$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> sendAction(String dataJson) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pipecat_flutter.PipecatClientApi.sendAction$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[dataJson]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class PipecatClientCallbacks {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onConnected();

  void onDisconnected();

  void onTransportStateChanged(String state);

  void onBotReady(BotReadyData botReadyData);

  void onBackendError(String message);

  void onLocalAudioLevel(double level);

  void onRemoteAudioLevel(double level, String participantId);

  void onBotStartedSpeaking();

  void onBotStoppedSpeaking();

  void onUserStartedSpeaking();

  void onUserStoppedSpeaking();

  void onUserTranscript(Transcript transcript);

  void onBotTranscript(String text);

  void onBotLlmText(String text);

  void onBotTtsText(String text);

  void onBotOutput(BotOutputData data);

  void onBotLlmStarted();

  void onBotLlmStopped();

  void onBotTtsStarted();

  void onBotTtsStopped();

  Future<String?> onLlmFunctionCall(LLMFunctionCallData data);

  void onMetrics(PipecatMetrics metrics);

  void onServerMessage(String dataJson);

  void onMessageError(String message);

  void onParticipantJoined(Participant participant);

  void onParticipantLeft(Participant participant);

  void onParticipantUpdated(Participant participant);

  void onTracksUpdated(Tracks tracks);

  void onAvailableCamsUpdated(List<MediaDeviceInfo?> cams);

  void onAvailableMicsUpdated(List<MediaDeviceInfo?> mics);

  void onAvailableSpeakersUpdated(List<MediaDeviceInfo?> speakers);

  void onCamUpdated(MediaDeviceInfo cam);

  void onMicUpdated(MediaDeviceInfo mic);

  void onSpeakerUpdated(MediaDeviceInfo speaker);

  void onBotLLMSearchResponse(BotLLMSearchResponseData response);

  void onBotConnected(Participant participant);

  void onBotDisconnected(Participant participant);

  void onBotStarted(String? dataJson);

  void onTrackStarted(String trackId, Participant participant);

  void onTrackStopped(String trackId, Participant participant);

  void onScreenTrackStarted(String trackId, Participant participant);

  void onScreenTrackStopped(String trackId, Participant participant);

  void onScreenShareError(String message);

  void onInputsUpdated(bool camera, bool mic);

  void onGenericError(String message, String? code);

  static void setUp(PipecatClientCallbacks? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onConnected$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onConnected();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onDisconnected$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onDisconnected();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onTransportStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onTransportStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_state = (args[0] as String?);
          assert(arg_state != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onTransportStateChanged was null, expected non-null String.');
          try {
            api.onTransportStateChanged(arg_state!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotReady$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotReady was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final BotReadyData? arg_botReadyData = (args[0] as BotReadyData?);
          assert(arg_botReadyData != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotReady was null, expected non-null BotReadyData.');
          try {
            api.onBotReady(arg_botReadyData!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBackendError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBackendError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_message = (args[0] as String?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBackendError was null, expected non-null String.');
          try {
            api.onBackendError(arg_message!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onLocalAudioLevel$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onLocalAudioLevel was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final double? arg_level = (args[0] as double?);
          assert(arg_level != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onLocalAudioLevel was null, expected non-null double.');
          try {
            api.onLocalAudioLevel(arg_level!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onRemoteAudioLevel$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onRemoteAudioLevel was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final double? arg_level = (args[0] as double?);
          assert(arg_level != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onRemoteAudioLevel was null, expected non-null double.');
          final String? arg_participantId = (args[1] as String?);
          assert(arg_participantId != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onRemoteAudioLevel was null, expected non-null String.');
          try {
            api.onRemoteAudioLevel(arg_level!, arg_participantId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotStartedSpeaking$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onBotStartedSpeaking();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotStoppedSpeaking$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onBotStoppedSpeaking();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onUserStartedSpeaking$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onUserStartedSpeaking();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onUserStoppedSpeaking$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onUserStoppedSpeaking();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onUserTranscript$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onUserTranscript was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final Transcript? arg_transcript = (args[0] as Transcript?);
          assert(arg_transcript != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onUserTranscript was null, expected non-null Transcript.');
          try {
            api.onUserTranscript(arg_transcript!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotTranscript$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotTranscript was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_text = (args[0] as String?);
          assert(arg_text != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotTranscript was null, expected non-null String.');
          try {
            api.onBotTranscript(arg_text!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotLlmText$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotLlmText was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_text = (args[0] as String?);
          assert(arg_text != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotLlmText was null, expected non-null String.');
          try {
            api.onBotLlmText(arg_text!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotTtsText$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotTtsText was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_text = (args[0] as String?);
          assert(arg_text != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotTtsText was null, expected non-null String.');
          try {
            api.onBotTtsText(arg_text!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotOutput$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotOutput was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final BotOutputData? arg_data = (args[0] as BotOutputData?);
          assert(arg_data != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotOutput was null, expected non-null BotOutputData.');
          try {
            api.onBotOutput(arg_data!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotLlmStarted$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onBotLlmStarted();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotLlmStopped$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onBotLlmStopped();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotTtsStarted$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onBotTtsStarted();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotTtsStopped$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onBotTtsStopped();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onLlmFunctionCall$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onLlmFunctionCall was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final LLMFunctionCallData? arg_data = (args[0] as LLMFunctionCallData?);
          assert(arg_data != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onLlmFunctionCall was null, expected non-null LLMFunctionCallData.');
          try {
            final String? output = await api.onLlmFunctionCall(arg_data!);
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onMetrics$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onMetrics was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final PipecatMetrics? arg_metrics = (args[0] as PipecatMetrics?);
          assert(arg_metrics != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onMetrics was null, expected non-null PipecatMetrics.');
          try {
            api.onMetrics(arg_metrics!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onServerMessage$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onServerMessage was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_dataJson = (args[0] as String?);
          assert(arg_dataJson != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onServerMessage was null, expected non-null String.');
          try {
            api.onServerMessage(arg_dataJson!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onMessageError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onMessageError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_message = (args[0] as String?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onMessageError was null, expected non-null String.');
          try {
            api.onMessageError(arg_message!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onParticipantJoined$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onParticipantJoined was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final Participant? arg_participant = (args[0] as Participant?);
          assert(arg_participant != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onParticipantJoined was null, expected non-null Participant.');
          try {
            api.onParticipantJoined(arg_participant!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onParticipantLeft$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onParticipantLeft was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final Participant? arg_participant = (args[0] as Participant?);
          assert(arg_participant != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onParticipantLeft was null, expected non-null Participant.');
          try {
            api.onParticipantLeft(arg_participant!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onParticipantUpdated$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onParticipantUpdated was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final Participant? arg_participant = (args[0] as Participant?);
          assert(arg_participant != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onParticipantUpdated was null, expected non-null Participant.');
          try {
            api.onParticipantUpdated(arg_participant!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onTracksUpdated$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onTracksUpdated was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final Tracks? arg_tracks = (args[0] as Tracks?);
          assert(arg_tracks != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onTracksUpdated was null, expected non-null Tracks.');
          try {
            api.onTracksUpdated(arg_tracks!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onAvailableCamsUpdated$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onAvailableCamsUpdated was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final List<MediaDeviceInfo?>? arg_cams = (args[0] as List<Object?>?)?.cast<MediaDeviceInfo?>();
          assert(arg_cams != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onAvailableCamsUpdated was null, expected non-null List<MediaDeviceInfo?>.');
          try {
            api.onAvailableCamsUpdated(arg_cams!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onAvailableMicsUpdated$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onAvailableMicsUpdated was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final List<MediaDeviceInfo?>? arg_mics = (args[0] as List<Object?>?)?.cast<MediaDeviceInfo?>();
          assert(arg_mics != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onAvailableMicsUpdated was null, expected non-null List<MediaDeviceInfo?>.');
          try {
            api.onAvailableMicsUpdated(arg_mics!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onAvailableSpeakersUpdated$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onAvailableSpeakersUpdated was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final List<MediaDeviceInfo?>? arg_speakers = (args[0] as List<Object?>?)?.cast<MediaDeviceInfo?>();
          assert(arg_speakers != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onAvailableSpeakersUpdated was null, expected non-null List<MediaDeviceInfo?>.');
          try {
            api.onAvailableSpeakersUpdated(arg_speakers!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onCamUpdated$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onCamUpdated was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final MediaDeviceInfo? arg_cam = (args[0] as MediaDeviceInfo?);
          assert(arg_cam != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onCamUpdated was null, expected non-null MediaDeviceInfo.');
          try {
            api.onCamUpdated(arg_cam!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onMicUpdated$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onMicUpdated was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final MediaDeviceInfo? arg_mic = (args[0] as MediaDeviceInfo?);
          assert(arg_mic != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onMicUpdated was null, expected non-null MediaDeviceInfo.');
          try {
            api.onMicUpdated(arg_mic!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onSpeakerUpdated$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onSpeakerUpdated was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final MediaDeviceInfo? arg_speaker = (args[0] as MediaDeviceInfo?);
          assert(arg_speaker != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onSpeakerUpdated was null, expected non-null MediaDeviceInfo.');
          try {
            api.onSpeakerUpdated(arg_speaker!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotLLMSearchResponse$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotLLMSearchResponse was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final BotLLMSearchResponseData? arg_response = (args[0] as BotLLMSearchResponseData?);
          assert(arg_response != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotLLMSearchResponse was null, expected non-null BotLLMSearchResponseData.');
          try {
            api.onBotLLMSearchResponse(arg_response!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotConnected$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotConnected was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final Participant? arg_participant = (args[0] as Participant?);
          assert(arg_participant != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotConnected was null, expected non-null Participant.');
          try {
            api.onBotConnected(arg_participant!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotDisconnected$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotDisconnected was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final Participant? arg_participant = (args[0] as Participant?);
          assert(arg_participant != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotDisconnected was null, expected non-null Participant.');
          try {
            api.onBotDisconnected(arg_participant!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotStarted$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onBotStarted was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_dataJson = (args[0] as String?);
          try {
            api.onBotStarted(arg_dataJson);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onTrackStarted$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onTrackStarted was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_trackId = (args[0] as String?);
          assert(arg_trackId != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onTrackStarted was null, expected non-null String.');
          final Participant? arg_participant = (args[1] as Participant?);
          assert(arg_participant != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onTrackStarted was null, expected non-null Participant.');
          try {
            api.onTrackStarted(arg_trackId!, arg_participant!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onTrackStopped$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onTrackStopped was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_trackId = (args[0] as String?);
          assert(arg_trackId != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onTrackStopped was null, expected non-null String.');
          final Participant? arg_participant = (args[1] as Participant?);
          assert(arg_participant != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onTrackStopped was null, expected non-null Participant.');
          try {
            api.onTrackStopped(arg_trackId!, arg_participant!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onScreenTrackStarted$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onScreenTrackStarted was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_trackId = (args[0] as String?);
          assert(arg_trackId != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onScreenTrackStarted was null, expected non-null String.');
          final Participant? arg_participant = (args[1] as Participant?);
          assert(arg_participant != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onScreenTrackStarted was null, expected non-null Participant.');
          try {
            api.onScreenTrackStarted(arg_trackId!, arg_participant!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onScreenTrackStopped$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onScreenTrackStopped was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_trackId = (args[0] as String?);
          assert(arg_trackId != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onScreenTrackStopped was null, expected non-null String.');
          final Participant? arg_participant = (args[1] as Participant?);
          assert(arg_participant != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onScreenTrackStopped was null, expected non-null Participant.');
          try {
            api.onScreenTrackStopped(arg_trackId!, arg_participant!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onScreenShareError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onScreenShareError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_message = (args[0] as String?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onScreenShareError was null, expected non-null String.');
          try {
            api.onScreenShareError(arg_message!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onInputsUpdated$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onInputsUpdated was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final bool? arg_camera = (args[0] as bool?);
          assert(arg_camera != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onInputsUpdated was null, expected non-null bool.');
          final bool? arg_mic = (args[1] as bool?);
          assert(arg_mic != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onInputsUpdated was null, expected non-null bool.');
          try {
            api.onInputsUpdated(arg_camera!, arg_mic!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onGenericError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onGenericError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_message = (args[0] as String?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.pipecat_flutter.PipecatClientCallbacks.onGenericError was null, expected non-null String.');
          final String? arg_code = (args[1] as String?);
          try {
            api.onGenericError(arg_message!, arg_code);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
